@startuml
'https://plantuml.com/use-case-diagram

:车企、电池租赁商: as 车企
:安全评估机构:
:电池生产商:
:回收企业:
:梯次利用企业:

package issuers {
actor 监管机构
'actor 平台
}

package credentials {
usecase 企业准入
'usecase 消费者准入
}

package verifiers {
actor 平台
}

监管机构 --> 企业准入 : 发行
企业准入 --> 车企
企业准入 --> 安全评估机构
企业准入 --> 电池生产商
企业准入 --> 回收企业
企业准入 --> 梯次利用企业

'平台 --> 消费者准入 : 发行
'消费者准入 --> 消费者

平台 -> 企业准入 : 验\n证

@enduml