@startuml
'https://plantuml.com/state-diagram'
title 电池状态机

'电池状态列表
初始化 : 电池生产
待安全审查 : 等待安全机构审查
正常 : 可组装/租赁
待回收 : 电池置换
回收中 : 第三方回收企业核验
梯次利用 : 回收核验去向之一
拆解 : 回收核验去向之一

[*] --> 初始化 : 电池生产
初始化 --> 待安全审查 : 安全机构审查
待安全审查 --> 正常 : 审查结束
正常 --> 正常 : 车企组装、消费者购车等
正常 --> 待回收 : 电池置换
待回收 --> 回收中 : 交给回收企业
回收中 --> 梯次利用 : 可梯次利用
回收中 --> 拆解 : 不可梯次利用
回收中 -> 正常 : 可再次使用
梯次利用 --> 拆解 : 不可梯次利用
拆解 --> [*]

@enduml