@startuml
'https://plantuml.com/state-diagram'
title 竞价交易状态机

'电池状态列表
竞价中 :
交易成功 :
交易失败 :

[*] --> 竞价中 : 交易发起
竞价中 -> 交易成功 : 达到期望交易金额 \n 或 \n 竞价时间结束且有高于最低期望金额
竞价中 --> 交易失败 : 主动撤回 \n 或 \n 竞价时间结束且没有高于最低期望金额
交易成功 --> [*]
交易失败 -> [*]

@enduml