version: "3"
networks:
  tars_net:
    external:
      name: tars-network
      
services:     
  tars-mysql:
    image: mysql:5.6
    platform: "linux/x86_64"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
      - "3310:3306"
    networks:
      tars_net:
        ipv4_address: 172.25.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ""
    restart: always

  tars-framework:
    image: tarscloud/framework:v3.0.1
    platform: "linux/x86_64"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      tars_net:
        ipv4_address: 172.25.0.3
    # 3000 is the tarsWeb port
    ports:
      - "3000:3000"
      - "3001:3001"
      - "20200-20205:20200-20205"
      - "30300-30305:30300-30305"
    environment:
      MYSQL_HOST: "172.25.0.2"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_PORT: 3306
      REBUILD: "false"
      INET: eth0
      SLAVE: "false"
    restart: always
    depends_on:
      - tars-mysql
