// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect.proto

package connect

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//学生信息初始化
type StuInfoInitInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=StuName,proto3" json:"StuName,omitempty"`
	UsName               string   `protobuf:"bytes,3,opt,name=UsName,proto3" json:"UsName,omitempty"`
	Major                string   `protobuf:"bytes,4,opt,name=Major,proto3" json:"Major,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuInfoInitInput) Reset()         { *m = StuInfoInitInput{} }
func (m *StuInfoInitInput) String() string { return proto.CompactTextString(m) }
func (*StuInfoInitInput) ProtoMessage()    {}
func (*StuInfoInitInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{0}
}

func (m *StuInfoInitInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuInfoInitInput.Unmarshal(m, b)
}
func (m *StuInfoInitInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuInfoInitInput.Marshal(b, m, deterministic)
}
func (m *StuInfoInitInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuInfoInitInput.Merge(m, src)
}
func (m *StuInfoInitInput) XXX_Size() int {
	return xxx_messageInfo_StuInfoInitInput.Size(m)
}
func (m *StuInfoInitInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuInfoInitInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuInfoInitInput proto.InternalMessageInfo

func (m *StuInfoInitInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuInfoInitInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuInfoInitInput) GetUsName() string {
	if m != nil {
		return m.UsName
	}
	return ""
}

func (m *StuInfoInitInput) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *StuInfoInitInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuInfoInitInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type StuInfoInitOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuInfoInitOutput) Reset()         { *m = StuInfoInitOutput{} }
func (m *StuInfoInitOutput) String() string { return proto.CompactTextString(m) }
func (*StuInfoInitOutput) ProtoMessage()    {}
func (*StuInfoInitOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{1}
}

func (m *StuInfoInitOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuInfoInitOutput.Unmarshal(m, b)
}
func (m *StuInfoInitOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuInfoInitOutput.Marshal(b, m, deterministic)
}
func (m *StuInfoInitOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuInfoInitOutput.Merge(m, src)
}
func (m *StuInfoInitOutput) XXX_Size() int {
	return xxx_messageInfo_StuInfoInitOutput.Size(m)
}
func (m *StuInfoInitOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuInfoInitOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuInfoInitOutput proto.InternalMessageInfo

func (m *StuInfoInitOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//学生信息更新
type StudentInfoUpdateInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=StuName,proto3" json:"StuName,omitempty"`
	UsName               string   `protobuf:"bytes,3,opt,name=UsName,proto3" json:"UsName,omitempty"`
	Major                string   `protobuf:"bytes,4,opt,name=Major,proto3" json:"Major,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentInfoUpdateInput) Reset()         { *m = StudentInfoUpdateInput{} }
func (m *StudentInfoUpdateInput) String() string { return proto.CompactTextString(m) }
func (*StudentInfoUpdateInput) ProtoMessage()    {}
func (*StudentInfoUpdateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{2}
}

func (m *StudentInfoUpdateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfoUpdateInput.Unmarshal(m, b)
}
func (m *StudentInfoUpdateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfoUpdateInput.Marshal(b, m, deterministic)
}
func (m *StudentInfoUpdateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfoUpdateInput.Merge(m, src)
}
func (m *StudentInfoUpdateInput) XXX_Size() int {
	return xxx_messageInfo_StudentInfoUpdateInput.Size(m)
}
func (m *StudentInfoUpdateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfoUpdateInput.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfoUpdateInput proto.InternalMessageInfo

func (m *StudentInfoUpdateInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StudentInfoUpdateInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StudentInfoUpdateInput) GetUsName() string {
	if m != nil {
		return m.UsName
	}
	return ""
}

func (m *StudentInfoUpdateInput) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *StudentInfoUpdateInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StudentInfoUpdateInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type StuInfoUpdateOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuInfoUpdateOutput) Reset()         { *m = StuInfoUpdateOutput{} }
func (m *StuInfoUpdateOutput) String() string { return proto.CompactTextString(m) }
func (*StuInfoUpdateOutput) ProtoMessage()    {}
func (*StuInfoUpdateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{3}
}

func (m *StuInfoUpdateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuInfoUpdateOutput.Unmarshal(m, b)
}
func (m *StuInfoUpdateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuInfoUpdateOutput.Marshal(b, m, deterministic)
}
func (m *StuInfoUpdateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuInfoUpdateOutput.Merge(m, src)
}
func (m *StuInfoUpdateOutput) XXX_Size() int {
	return xxx_messageInfo_StuInfoUpdateOutput.Size(m)
}
func (m *StuInfoUpdateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuInfoUpdateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuInfoUpdateOutput proto.InternalMessageInfo

func (m *StuInfoUpdateOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//各学期成绩录入
type StuGradeRecodeInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=StuName,proto3" json:"StuName,omitempty"`
	Term                 uint32   `protobuf:"varint,3,opt,name=Term,proto3" json:"Term,omitempty"`
	AverageGrades        uint32   `protobuf:"varint,4,opt,name=AverageGrades,proto3" json:"AverageGrades,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuGradeRecodeInput) Reset()         { *m = StuGradeRecodeInput{} }
func (m *StuGradeRecodeInput) String() string { return proto.CompactTextString(m) }
func (*StuGradeRecodeInput) ProtoMessage()    {}
func (*StuGradeRecodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{4}
}

func (m *StuGradeRecodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuGradeRecodeInput.Unmarshal(m, b)
}
func (m *StuGradeRecodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuGradeRecodeInput.Marshal(b, m, deterministic)
}
func (m *StuGradeRecodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuGradeRecodeInput.Merge(m, src)
}
func (m *StuGradeRecodeInput) XXX_Size() int {
	return xxx_messageInfo_StuGradeRecodeInput.Size(m)
}
func (m *StuGradeRecodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuGradeRecodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuGradeRecodeInput proto.InternalMessageInfo

func (m *StuGradeRecodeInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuGradeRecodeInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuGradeRecodeInput) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *StuGradeRecodeInput) GetAverageGrades() uint32 {
	if m != nil {
		return m.AverageGrades
	}
	return 0
}

func (m *StuGradeRecodeInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuGradeRecodeInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type StuGradeRecodeOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuGradeRecodeOutput) Reset()         { *m = StuGradeRecodeOutput{} }
func (m *StuGradeRecodeOutput) String() string { return proto.CompactTextString(m) }
func (*StuGradeRecodeOutput) ProtoMessage()    {}
func (*StuGradeRecodeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{5}
}

func (m *StuGradeRecodeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuGradeRecodeOutput.Unmarshal(m, b)
}
func (m *StuGradeRecodeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuGradeRecodeOutput.Marshal(b, m, deterministic)
}
func (m *StuGradeRecodeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuGradeRecodeOutput.Merge(m, src)
}
func (m *StuGradeRecodeOutput) XXX_Size() int {
	return xxx_messageInfo_StuGradeRecodeOutput.Size(m)
}
func (m *StuGradeRecodeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuGradeRecodeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuGradeRecodeOutput proto.InternalMessageInfo

func (m *StuGradeRecodeOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//各学期成绩更新
type StuGradeUpdateInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=StuName,proto3" json:"StuName,omitempty"`
	Term                 uint32   `protobuf:"varint,3,opt,name=Term,proto3" json:"Term,omitempty"`
	AverageGrades        uint32   `protobuf:"varint,4,opt,name=AverageGrades,proto3" json:"AverageGrades,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuGradeUpdateInput) Reset()         { *m = StuGradeUpdateInput{} }
func (m *StuGradeUpdateInput) String() string { return proto.CompactTextString(m) }
func (*StuGradeUpdateInput) ProtoMessage()    {}
func (*StuGradeUpdateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{6}
}

func (m *StuGradeUpdateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuGradeUpdateInput.Unmarshal(m, b)
}
func (m *StuGradeUpdateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuGradeUpdateInput.Marshal(b, m, deterministic)
}
func (m *StuGradeUpdateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuGradeUpdateInput.Merge(m, src)
}
func (m *StuGradeUpdateInput) XXX_Size() int {
	return xxx_messageInfo_StuGradeUpdateInput.Size(m)
}
func (m *StuGradeUpdateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuGradeUpdateInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuGradeUpdateInput proto.InternalMessageInfo

func (m *StuGradeUpdateInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuGradeUpdateInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuGradeUpdateInput) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *StuGradeUpdateInput) GetAverageGrades() uint32 {
	if m != nil {
		return m.AverageGrades
	}
	return 0
}

func (m *StuGradeUpdateInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuGradeUpdateInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type StuGradeUpdateOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuGradeUpdateOutput) Reset()         { *m = StuGradeUpdateOutput{} }
func (m *StuGradeUpdateOutput) String() string { return proto.CompactTextString(m) }
func (*StuGradeUpdateOutput) ProtoMessage()    {}
func (*StuGradeUpdateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{7}
}

func (m *StuGradeUpdateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuGradeUpdateOutput.Unmarshal(m, b)
}
func (m *StuGradeUpdateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuGradeUpdateOutput.Marshal(b, m, deterministic)
}
func (m *StuGradeUpdateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuGradeUpdateOutput.Merge(m, src)
}
func (m *StuGradeUpdateOutput) XXX_Size() int {
	return xxx_messageInfo_StuGradeUpdateOutput.Size(m)
}
func (m *StuGradeUpdateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuGradeUpdateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuGradeUpdateOutput proto.InternalMessageInfo

func (m *StuGradeUpdateOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//活动发布
type ActivityRegisterInput struct {
	ActID                uint32   `protobuf:"varint,1,opt,name=ActID,proto3" json:"ActID,omitempty"`
	ActName              string   `protobuf:"bytes,2,opt,name=ActName,proto3" json:"ActName,omitempty"`
	Sponsor              string   `protobuf:"bytes,3,opt,name=Sponsor,proto3" json:"Sponsor,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityRegisterInput) Reset()         { *m = ActivityRegisterInput{} }
func (m *ActivityRegisterInput) String() string { return proto.CompactTextString(m) }
func (*ActivityRegisterInput) ProtoMessage()    {}
func (*ActivityRegisterInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{8}
}

func (m *ActivityRegisterInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityRegisterInput.Unmarshal(m, b)
}
func (m *ActivityRegisterInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityRegisterInput.Marshal(b, m, deterministic)
}
func (m *ActivityRegisterInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityRegisterInput.Merge(m, src)
}
func (m *ActivityRegisterInput) XXX_Size() int {
	return xxx_messageInfo_ActivityRegisterInput.Size(m)
}
func (m *ActivityRegisterInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityRegisterInput.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityRegisterInput proto.InternalMessageInfo

func (m *ActivityRegisterInput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

func (m *ActivityRegisterInput) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *ActivityRegisterInput) GetSponsor() string {
	if m != nil {
		return m.Sponsor
	}
	return ""
}

func (m *ActivityRegisterInput) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ActivityRegisterInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *ActivityRegisterInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ActivityRegisterOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityRegisterOutput) Reset()         { *m = ActivityRegisterOutput{} }
func (m *ActivityRegisterOutput) String() string { return proto.CompactTextString(m) }
func (*ActivityRegisterOutput) ProtoMessage()    {}
func (*ActivityRegisterOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{9}
}

func (m *ActivityRegisterOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityRegisterOutput.Unmarshal(m, b)
}
func (m *ActivityRegisterOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityRegisterOutput.Marshal(b, m, deterministic)
}
func (m *ActivityRegisterOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityRegisterOutput.Merge(m, src)
}
func (m *ActivityRegisterOutput) XXX_Size() int {
	return xxx_messageInfo_ActivityRegisterOutput.Size(m)
}
func (m *ActivityRegisterOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityRegisterOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityRegisterOutput proto.InternalMessageInfo

func (m *ActivityRegisterOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//活动信息更新
type ActivityInfoUpdateInput struct {
	ActID                uint32   `protobuf:"varint,1,opt,name=ActID,proto3" json:"ActID,omitempty"`
	ActName              string   `protobuf:"bytes,2,opt,name=ActName,proto3" json:"ActName,omitempty"`
	Sponsor              string   `protobuf:"bytes,3,opt,name=Sponsor,proto3" json:"Sponsor,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityInfoUpdateInput) Reset()         { *m = ActivityInfoUpdateInput{} }
func (m *ActivityInfoUpdateInput) String() string { return proto.CompactTextString(m) }
func (*ActivityInfoUpdateInput) ProtoMessage()    {}
func (*ActivityInfoUpdateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{10}
}

func (m *ActivityInfoUpdateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityInfoUpdateInput.Unmarshal(m, b)
}
func (m *ActivityInfoUpdateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityInfoUpdateInput.Marshal(b, m, deterministic)
}
func (m *ActivityInfoUpdateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityInfoUpdateInput.Merge(m, src)
}
func (m *ActivityInfoUpdateInput) XXX_Size() int {
	return xxx_messageInfo_ActivityInfoUpdateInput.Size(m)
}
func (m *ActivityInfoUpdateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityInfoUpdateInput.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityInfoUpdateInput proto.InternalMessageInfo

func (m *ActivityInfoUpdateInput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

func (m *ActivityInfoUpdateInput) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *ActivityInfoUpdateInput) GetSponsor() string {
	if m != nil {
		return m.Sponsor
	}
	return ""
}

func (m *ActivityInfoUpdateInput) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ActivityInfoUpdateInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *ActivityInfoUpdateInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ActivityInfoUpdateOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityInfoUpdateOutput) Reset()         { *m = ActivityInfoUpdateOutput{} }
func (m *ActivityInfoUpdateOutput) String() string { return proto.CompactTextString(m) }
func (*ActivityInfoUpdateOutput) ProtoMessage()    {}
func (*ActivityInfoUpdateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{11}
}

func (m *ActivityInfoUpdateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityInfoUpdateOutput.Unmarshal(m, b)
}
func (m *ActivityInfoUpdateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityInfoUpdateOutput.Marshal(b, m, deterministic)
}
func (m *ActivityInfoUpdateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityInfoUpdateOutput.Merge(m, src)
}
func (m *ActivityInfoUpdateOutput) XXX_Size() int {
	return xxx_messageInfo_ActivityInfoUpdateOutput.Size(m)
}
func (m *ActivityInfoUpdateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityInfoUpdateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityInfoUpdateOutput proto.InternalMessageInfo

func (m *ActivityInfoUpdateOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//活动成绩记录
type ActivityGradeRecodeInput struct {
	ActID                uint32   `protobuf:"varint,1,opt,name=ActID,proto3" json:"ActID,omitempty"`
	StuID                uint64   `protobuf:"varint,2,opt,name=StuID,proto3" json:"StuID,omitempty"`
	ActName              string   `protobuf:"bytes,3,opt,name=ActName,proto3" json:"ActName,omitempty"`
	StuName              string   `protobuf:"bytes,4,opt,name=StuName,proto3" json:"StuName,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	ActSignature         string   `protobuf:"bytes,7,opt,name=ActSignature,proto3" json:"ActSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityGradeRecodeInput) Reset()         { *m = ActivityGradeRecodeInput{} }
func (m *ActivityGradeRecodeInput) String() string { return proto.CompactTextString(m) }
func (*ActivityGradeRecodeInput) ProtoMessage()    {}
func (*ActivityGradeRecodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{12}
}

func (m *ActivityGradeRecodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityGradeRecodeInput.Unmarshal(m, b)
}
func (m *ActivityGradeRecodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityGradeRecodeInput.Marshal(b, m, deterministic)
}
func (m *ActivityGradeRecodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityGradeRecodeInput.Merge(m, src)
}
func (m *ActivityGradeRecodeInput) XXX_Size() int {
	return xxx_messageInfo_ActivityGradeRecodeInput.Size(m)
}
func (m *ActivityGradeRecodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityGradeRecodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityGradeRecodeInput proto.InternalMessageInfo

func (m *ActivityGradeRecodeInput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

func (m *ActivityGradeRecodeInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *ActivityGradeRecodeInput) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *ActivityGradeRecodeInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *ActivityGradeRecodeInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *ActivityGradeRecodeInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ActivityGradeRecodeInput) GetActSignature() string {
	if m != nil {
		return m.ActSignature
	}
	return ""
}

type ActivityGradeRecodeOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityGradeRecodeOutput) Reset()         { *m = ActivityGradeRecodeOutput{} }
func (m *ActivityGradeRecodeOutput) String() string { return proto.CompactTextString(m) }
func (*ActivityGradeRecodeOutput) ProtoMessage()    {}
func (*ActivityGradeRecodeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{13}
}

func (m *ActivityGradeRecodeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityGradeRecodeOutput.Unmarshal(m, b)
}
func (m *ActivityGradeRecodeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityGradeRecodeOutput.Marshal(b, m, deterministic)
}
func (m *ActivityGradeRecodeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityGradeRecodeOutput.Merge(m, src)
}
func (m *ActivityGradeRecodeOutput) XXX_Size() int {
	return xxx_messageInfo_ActivityGradeRecodeOutput.Size(m)
}
func (m *ActivityGradeRecodeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityGradeRecodeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityGradeRecodeOutput proto.InternalMessageInfo

func (m *ActivityGradeRecodeOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//证书信息初始化
type CertInfoInitInput struct {
	CertID               uint64   `protobuf:"varint,1,opt,name=CertID,proto3" json:"CertID,omitempty"`
	StuID                uint64   `protobuf:"varint,2,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,3,opt,name=StuName,proto3" json:"StuName,omitempty"`
	UsName               string   `protobuf:"bytes,4,opt,name=UsName,proto3" json:"UsName,omitempty"`
	Major                string   `protobuf:"bytes,5,opt,name=Major,proto3" json:"Major,omitempty"`
	StudyTime            string   `protobuf:"bytes,6,opt,name=StudyTime,proto3" json:"StudyTime,omitempty"`
	CertStatus           string   `protobuf:"bytes,7,opt,name=CertStatus,proto3" json:"CertStatus,omitempty"`
	ExtInfo              string   `protobuf:"bytes,8,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,9,opt,name=Time,proto3" json:"Time,omitempty"`
	CertSignature        string   `protobuf:"bytes,10,opt,name=CertSignature,proto3" json:"CertSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertInfoInitInput) Reset()         { *m = CertInfoInitInput{} }
func (m *CertInfoInitInput) String() string { return proto.CompactTextString(m) }
func (*CertInfoInitInput) ProtoMessage()    {}
func (*CertInfoInitInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{14}
}

func (m *CertInfoInitInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertInfoInitInput.Unmarshal(m, b)
}
func (m *CertInfoInitInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertInfoInitInput.Marshal(b, m, deterministic)
}
func (m *CertInfoInitInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertInfoInitInput.Merge(m, src)
}
func (m *CertInfoInitInput) XXX_Size() int {
	return xxx_messageInfo_CertInfoInitInput.Size(m)
}
func (m *CertInfoInitInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CertInfoInitInput.DiscardUnknown(m)
}

var xxx_messageInfo_CertInfoInitInput proto.InternalMessageInfo

func (m *CertInfoInitInput) GetCertID() uint64 {
	if m != nil {
		return m.CertID
	}
	return 0
}

func (m *CertInfoInitInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *CertInfoInitInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *CertInfoInitInput) GetUsName() string {
	if m != nil {
		return m.UsName
	}
	return ""
}

func (m *CertInfoInitInput) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *CertInfoInitInput) GetStudyTime() string {
	if m != nil {
		return m.StudyTime
	}
	return ""
}

func (m *CertInfoInitInput) GetCertStatus() string {
	if m != nil {
		return m.CertStatus
	}
	return ""
}

func (m *CertInfoInitInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *CertInfoInitInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CertInfoInitInput) GetCertSignature() string {
	if m != nil {
		return m.CertSignature
	}
	return ""
}

type CertInfoInitOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertInfoInitOutput) Reset()         { *m = CertInfoInitOutput{} }
func (m *CertInfoInitOutput) String() string { return proto.CompactTextString(m) }
func (*CertInfoInitOutput) ProtoMessage()    {}
func (*CertInfoInitOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{15}
}

func (m *CertInfoInitOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertInfoInitOutput.Unmarshal(m, b)
}
func (m *CertInfoInitOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertInfoInitOutput.Marshal(b, m, deterministic)
}
func (m *CertInfoInitOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertInfoInitOutput.Merge(m, src)
}
func (m *CertInfoInitOutput) XXX_Size() int {
	return xxx_messageInfo_CertInfoInitOutput.Size(m)
}
func (m *CertInfoInitOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CertInfoInitOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CertInfoInitOutput proto.InternalMessageInfo

func (m *CertInfoInitOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//证书信息更新
type CertInfoUpdateInput struct {
	CertID               uint64   `protobuf:"varint,1,opt,name=CertID,proto3" json:"CertID,omitempty"`
	StuID                uint64   `protobuf:"varint,2,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,3,opt,name=StuName,proto3" json:"StuName,omitempty"`
	UsName               string   `protobuf:"bytes,4,opt,name=UsName,proto3" json:"UsName,omitempty"`
	Major                string   `protobuf:"bytes,5,opt,name=Major,proto3" json:"Major,omitempty"`
	StudyTime            string   `protobuf:"bytes,6,opt,name=StudyTime,proto3" json:"StudyTime,omitempty"`
	CertStatus           string   `protobuf:"bytes,7,opt,name=CertStatus,proto3" json:"CertStatus,omitempty"`
	ExtInfo              string   `protobuf:"bytes,8,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,9,opt,name=Time,proto3" json:"Time,omitempty"`
	CertSignature        string   `protobuf:"bytes,10,opt,name=CertSignature,proto3" json:"CertSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertInfoUpdateInput) Reset()         { *m = CertInfoUpdateInput{} }
func (m *CertInfoUpdateInput) String() string { return proto.CompactTextString(m) }
func (*CertInfoUpdateInput) ProtoMessage()    {}
func (*CertInfoUpdateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{16}
}

func (m *CertInfoUpdateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertInfoUpdateInput.Unmarshal(m, b)
}
func (m *CertInfoUpdateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertInfoUpdateInput.Marshal(b, m, deterministic)
}
func (m *CertInfoUpdateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertInfoUpdateInput.Merge(m, src)
}
func (m *CertInfoUpdateInput) XXX_Size() int {
	return xxx_messageInfo_CertInfoUpdateInput.Size(m)
}
func (m *CertInfoUpdateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CertInfoUpdateInput.DiscardUnknown(m)
}

var xxx_messageInfo_CertInfoUpdateInput proto.InternalMessageInfo

func (m *CertInfoUpdateInput) GetCertID() uint64 {
	if m != nil {
		return m.CertID
	}
	return 0
}

func (m *CertInfoUpdateInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *CertInfoUpdateInput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *CertInfoUpdateInput) GetUsName() string {
	if m != nil {
		return m.UsName
	}
	return ""
}

func (m *CertInfoUpdateInput) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *CertInfoUpdateInput) GetStudyTime() string {
	if m != nil {
		return m.StudyTime
	}
	return ""
}

func (m *CertInfoUpdateInput) GetCertStatus() string {
	if m != nil {
		return m.CertStatus
	}
	return ""
}

func (m *CertInfoUpdateInput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *CertInfoUpdateInput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CertInfoUpdateInput) GetCertSignature() string {
	if m != nil {
		return m.CertSignature
	}
	return ""
}

type CertInfoUpdateOutput struct {
	Success              string   `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertInfoUpdateOutput) Reset()         { *m = CertInfoUpdateOutput{} }
func (m *CertInfoUpdateOutput) String() string { return proto.CompactTextString(m) }
func (*CertInfoUpdateOutput) ProtoMessage()    {}
func (*CertInfoUpdateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{17}
}

func (m *CertInfoUpdateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertInfoUpdateOutput.Unmarshal(m, b)
}
func (m *CertInfoUpdateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertInfoUpdateOutput.Marshal(b, m, deterministic)
}
func (m *CertInfoUpdateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertInfoUpdateOutput.Merge(m, src)
}
func (m *CertInfoUpdateOutput) XXX_Size() int {
	return xxx_messageInfo_CertInfoUpdateOutput.Size(m)
}
func (m *CertInfoUpdateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CertInfoUpdateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CertInfoUpdateOutput proto.InternalMessageInfo

func (m *CertInfoUpdateOutput) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

//学生信息查询
type StuInfoQueryInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuInfoQueryInput) Reset()         { *m = StuInfoQueryInput{} }
func (m *StuInfoQueryInput) String() string { return proto.CompactTextString(m) }
func (*StuInfoQueryInput) ProtoMessage()    {}
func (*StuInfoQueryInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{18}
}

func (m *StuInfoQueryInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuInfoQueryInput.Unmarshal(m, b)
}
func (m *StuInfoQueryInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuInfoQueryInput.Marshal(b, m, deterministic)
}
func (m *StuInfoQueryInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuInfoQueryInput.Merge(m, src)
}
func (m *StuInfoQueryInput) XXX_Size() int {
	return xxx_messageInfo_StuInfoQueryInput.Size(m)
}
func (m *StuInfoQueryInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuInfoQueryInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuInfoQueryInput proto.InternalMessageInfo

func (m *StuInfoQueryInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

type StuInfoQueryOutput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=StuName,proto3" json:"StuName,omitempty"`
	UsName               string   `protobuf:"bytes,3,opt,name=UsName,proto3" json:"UsName,omitempty"`
	Major                string   `protobuf:"bytes,4,opt,name=Major,proto3" json:"Major,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuInfoQueryOutput) Reset()         { *m = StuInfoQueryOutput{} }
func (m *StuInfoQueryOutput) String() string { return proto.CompactTextString(m) }
func (*StuInfoQueryOutput) ProtoMessage()    {}
func (*StuInfoQueryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{19}
}

func (m *StuInfoQueryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuInfoQueryOutput.Unmarshal(m, b)
}
func (m *StuInfoQueryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuInfoQueryOutput.Marshal(b, m, deterministic)
}
func (m *StuInfoQueryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuInfoQueryOutput.Merge(m, src)
}
func (m *StuInfoQueryOutput) XXX_Size() int {
	return xxx_messageInfo_StuInfoQueryOutput.Size(m)
}
func (m *StuInfoQueryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuInfoQueryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuInfoQueryOutput proto.InternalMessageInfo

func (m *StuInfoQueryOutput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuInfoQueryOutput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuInfoQueryOutput) GetUsName() string {
	if m != nil {
		return m.UsName
	}
	return ""
}

func (m *StuInfoQueryOutput) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *StuInfoQueryOutput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuInfoQueryOutput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

//学生成绩查询
type StuGradeQueryInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	Term                 uint32   `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuGradeQueryInput) Reset()         { *m = StuGradeQueryInput{} }
func (m *StuGradeQueryInput) String() string { return proto.CompactTextString(m) }
func (*StuGradeQueryInput) ProtoMessage()    {}
func (*StuGradeQueryInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{20}
}

func (m *StuGradeQueryInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuGradeQueryInput.Unmarshal(m, b)
}
func (m *StuGradeQueryInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuGradeQueryInput.Marshal(b, m, deterministic)
}
func (m *StuGradeQueryInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuGradeQueryInput.Merge(m, src)
}
func (m *StuGradeQueryInput) XXX_Size() int {
	return xxx_messageInfo_StuGradeQueryInput.Size(m)
}
func (m *StuGradeQueryInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuGradeQueryInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuGradeQueryInput proto.InternalMessageInfo

func (m *StuGradeQueryInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuGradeQueryInput) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

type StuGradeQueryOutput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=StuName,proto3" json:"StuName,omitempty"`
	Term                 uint32   `protobuf:"varint,3,opt,name=Term,proto3" json:"Term,omitempty"`
	AverageGrades        uint32   `protobuf:"varint,4,opt,name=AverageGrades,proto3" json:"AverageGrades,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuGradeQueryOutput) Reset()         { *m = StuGradeQueryOutput{} }
func (m *StuGradeQueryOutput) String() string { return proto.CompactTextString(m) }
func (*StuGradeQueryOutput) ProtoMessage()    {}
func (*StuGradeQueryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{21}
}

func (m *StuGradeQueryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuGradeQueryOutput.Unmarshal(m, b)
}
func (m *StuGradeQueryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuGradeQueryOutput.Marshal(b, m, deterministic)
}
func (m *StuGradeQueryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuGradeQueryOutput.Merge(m, src)
}
func (m *StuGradeQueryOutput) XXX_Size() int {
	return xxx_messageInfo_StuGradeQueryOutput.Size(m)
}
func (m *StuGradeQueryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuGradeQueryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuGradeQueryOutput proto.InternalMessageInfo

func (m *StuGradeQueryOutput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuGradeQueryOutput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuGradeQueryOutput) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *StuGradeQueryOutput) GetAverageGrades() uint32 {
	if m != nil {
		return m.AverageGrades
	}
	return 0
}

func (m *StuGradeQueryOutput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuGradeQueryOutput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

//学生活动查询
type StuActQueryInput struct {
	StuID                uint64   `protobuf:"varint,1,opt,name=StuID,proto3" json:"StuID,omitempty"`
	ActID                uint32   `protobuf:"varint,2,opt,name=ActID,proto3" json:"ActID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuActQueryInput) Reset()         { *m = StuActQueryInput{} }
func (m *StuActQueryInput) String() string { return proto.CompactTextString(m) }
func (*StuActQueryInput) ProtoMessage()    {}
func (*StuActQueryInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{22}
}

func (m *StuActQueryInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuActQueryInput.Unmarshal(m, b)
}
func (m *StuActQueryInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuActQueryInput.Marshal(b, m, deterministic)
}
func (m *StuActQueryInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuActQueryInput.Merge(m, src)
}
func (m *StuActQueryInput) XXX_Size() int {
	return xxx_messageInfo_StuActQueryInput.Size(m)
}
func (m *StuActQueryInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuActQueryInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuActQueryInput proto.InternalMessageInfo

func (m *StuActQueryInput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuActQueryInput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

type StuActQueryOutput struct {
	ActID                uint32   `protobuf:"varint,1,opt,name=actID,proto3" json:"actID,omitempty"`
	StuID                uint64   `protobuf:"varint,2,opt,name=stuID,proto3" json:"stuID,omitempty"`
	ActName              string   `protobuf:"bytes,3,opt,name=actName,proto3" json:"actName,omitempty"`
	StuName              string   `protobuf:"bytes,4,opt,name=stuName,proto3" json:"stuName,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=extInfo,proto3" json:"extInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	ActSignature         string   `protobuf:"bytes,7,opt,name=actSignature,proto3" json:"actSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuActQueryOutput) Reset()         { *m = StuActQueryOutput{} }
func (m *StuActQueryOutput) String() string { return proto.CompactTextString(m) }
func (*StuActQueryOutput) ProtoMessage()    {}
func (*StuActQueryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{23}
}

func (m *StuActQueryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuActQueryOutput.Unmarshal(m, b)
}
func (m *StuActQueryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuActQueryOutput.Marshal(b, m, deterministic)
}
func (m *StuActQueryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuActQueryOutput.Merge(m, src)
}
func (m *StuActQueryOutput) XXX_Size() int {
	return xxx_messageInfo_StuActQueryOutput.Size(m)
}
func (m *StuActQueryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuActQueryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuActQueryOutput proto.InternalMessageInfo

func (m *StuActQueryOutput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

func (m *StuActQueryOutput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuActQueryOutput) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *StuActQueryOutput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuActQueryOutput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuActQueryOutput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *StuActQueryOutput) GetActSignature() string {
	if m != nil {
		return m.ActSignature
	}
	return ""
}

//学生证书查询
type StuCertQueryInput struct {
	CertID               uint64   `protobuf:"varint,1,opt,name=CertID,proto3" json:"CertID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuCertQueryInput) Reset()         { *m = StuCertQueryInput{} }
func (m *StuCertQueryInput) String() string { return proto.CompactTextString(m) }
func (*StuCertQueryInput) ProtoMessage()    {}
func (*StuCertQueryInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{24}
}

func (m *StuCertQueryInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuCertQueryInput.Unmarshal(m, b)
}
func (m *StuCertQueryInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuCertQueryInput.Marshal(b, m, deterministic)
}
func (m *StuCertQueryInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuCertQueryInput.Merge(m, src)
}
func (m *StuCertQueryInput) XXX_Size() int {
	return xxx_messageInfo_StuCertQueryInput.Size(m)
}
func (m *StuCertQueryInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuCertQueryInput.DiscardUnknown(m)
}

var xxx_messageInfo_StuCertQueryInput proto.InternalMessageInfo

func (m *StuCertQueryInput) GetCertID() uint64 {
	if m != nil {
		return m.CertID
	}
	return 0
}

type StuCertQueryOutput struct {
	CertID               uint64   `protobuf:"varint,1,opt,name=CertID,proto3" json:"CertID,omitempty"`
	StuID                uint64   `protobuf:"varint,2,opt,name=StuID,proto3" json:"StuID,omitempty"`
	StuName              string   `protobuf:"bytes,3,opt,name=StuName,proto3" json:"StuName,omitempty"`
	UsName               string   `protobuf:"bytes,4,opt,name=UsName,proto3" json:"UsName,omitempty"`
	Major                string   `protobuf:"bytes,5,opt,name=Major,proto3" json:"Major,omitempty"`
	StudyTime            string   `protobuf:"bytes,6,opt,name=StudyTime,proto3" json:"StudyTime,omitempty"`
	CertStatus           string   `protobuf:"bytes,7,opt,name=CertStatus,proto3" json:"CertStatus,omitempty"`
	ExtInfo              string   `protobuf:"bytes,8,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,9,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StuCertQueryOutput) Reset()         { *m = StuCertQueryOutput{} }
func (m *StuCertQueryOutput) String() string { return proto.CompactTextString(m) }
func (*StuCertQueryOutput) ProtoMessage()    {}
func (*StuCertQueryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{25}
}

func (m *StuCertQueryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StuCertQueryOutput.Unmarshal(m, b)
}
func (m *StuCertQueryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StuCertQueryOutput.Marshal(b, m, deterministic)
}
func (m *StuCertQueryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StuCertQueryOutput.Merge(m, src)
}
func (m *StuCertQueryOutput) XXX_Size() int {
	return xxx_messageInfo_StuCertQueryOutput.Size(m)
}
func (m *StuCertQueryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StuCertQueryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StuCertQueryOutput proto.InternalMessageInfo

func (m *StuCertQueryOutput) GetCertID() uint64 {
	if m != nil {
		return m.CertID
	}
	return 0
}

func (m *StuCertQueryOutput) GetStuID() uint64 {
	if m != nil {
		return m.StuID
	}
	return 0
}

func (m *StuCertQueryOutput) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StuCertQueryOutput) GetUsName() string {
	if m != nil {
		return m.UsName
	}
	return ""
}

func (m *StuCertQueryOutput) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *StuCertQueryOutput) GetStudyTime() string {
	if m != nil {
		return m.StudyTime
	}
	return ""
}

func (m *StuCertQueryOutput) GetCertStatus() string {
	if m != nil {
		return m.CertStatus
	}
	return ""
}

func (m *StuCertQueryOutput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *StuCertQueryOutput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

//活动信息查询
type ActInfoQueryInput struct {
	ActID                uint32   `protobuf:"varint,1,opt,name=actID,proto3" json:"actID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActInfoQueryInput) Reset()         { *m = ActInfoQueryInput{} }
func (m *ActInfoQueryInput) String() string { return proto.CompactTextString(m) }
func (*ActInfoQueryInput) ProtoMessage()    {}
func (*ActInfoQueryInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{26}
}

func (m *ActInfoQueryInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActInfoQueryInput.Unmarshal(m, b)
}
func (m *ActInfoQueryInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActInfoQueryInput.Marshal(b, m, deterministic)
}
func (m *ActInfoQueryInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActInfoQueryInput.Merge(m, src)
}
func (m *ActInfoQueryInput) XXX_Size() int {
	return xxx_messageInfo_ActInfoQueryInput.Size(m)
}
func (m *ActInfoQueryInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActInfoQueryInput.DiscardUnknown(m)
}

var xxx_messageInfo_ActInfoQueryInput proto.InternalMessageInfo

func (m *ActInfoQueryInput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

type ActInfoQueryOutput struct {
	ActID                uint32   `protobuf:"varint,1,opt,name=ActID,proto3" json:"ActID,omitempty"`
	ActName              string   `protobuf:"bytes,2,opt,name=ActName,proto3" json:"ActName,omitempty"`
	Sponsor              string   `protobuf:"bytes,3,opt,name=Sponsor,proto3" json:"Sponsor,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	ExtInfo              string   `protobuf:"bytes,5,opt,name=ExtInfo,proto3" json:"ExtInfo,omitempty"`
	Time                 uint64   `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActInfoQueryOutput) Reset()         { *m = ActInfoQueryOutput{} }
func (m *ActInfoQueryOutput) String() string { return proto.CompactTextString(m) }
func (*ActInfoQueryOutput) ProtoMessage()    {}
func (*ActInfoQueryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{27}
}

func (m *ActInfoQueryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActInfoQueryOutput.Unmarshal(m, b)
}
func (m *ActInfoQueryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActInfoQueryOutput.Marshal(b, m, deterministic)
}
func (m *ActInfoQueryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActInfoQueryOutput.Merge(m, src)
}
func (m *ActInfoQueryOutput) XXX_Size() int {
	return xxx_messageInfo_ActInfoQueryOutput.Size(m)
}
func (m *ActInfoQueryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActInfoQueryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ActInfoQueryOutput proto.InternalMessageInfo

func (m *ActInfoQueryOutput) GetActID() uint32 {
	if m != nil {
		return m.ActID
	}
	return 0
}

func (m *ActInfoQueryOutput) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *ActInfoQueryOutput) GetSponsor() string {
	if m != nil {
		return m.Sponsor
	}
	return ""
}

func (m *ActInfoQueryOutput) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ActInfoQueryOutput) GetExtInfo() string {
	if m != nil {
		return m.ExtInfo
	}
	return ""
}

func (m *ActInfoQueryOutput) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*StuInfoInitInput)(nil), "StuInfoInitInput")
	proto.RegisterType((*StuInfoInitOutput)(nil), "StuInfoInitOutput")
	proto.RegisterType((*StudentInfoUpdateInput)(nil), "StudentInfoUpdateInput")
	proto.RegisterType((*StuInfoUpdateOutput)(nil), "StuInfoUpdateOutput")
	proto.RegisterType((*StuGradeRecodeInput)(nil), "StuGradeRecodeInput")
	proto.RegisterType((*StuGradeRecodeOutput)(nil), "StuGradeRecodeOutput")
	proto.RegisterType((*StuGradeUpdateInput)(nil), "StuGradeUpdateInput")
	proto.RegisterType((*StuGradeUpdateOutput)(nil), "StuGradeUpdateOutput")
	proto.RegisterType((*ActivityRegisterInput)(nil), "ActivityRegisterInput")
	proto.RegisterType((*ActivityRegisterOutput)(nil), "ActivityRegisterOutput")
	proto.RegisterType((*ActivityInfoUpdateInput)(nil), "ActivityInfoUpdateInput")
	proto.RegisterType((*ActivityInfoUpdateOutput)(nil), "ActivityInfoUpdateOutput")
	proto.RegisterType((*ActivityGradeRecodeInput)(nil), "ActivityGradeRecodeInput")
	proto.RegisterType((*ActivityGradeRecodeOutput)(nil), "ActivityGradeRecodeOutput")
	proto.RegisterType((*CertInfoInitInput)(nil), "CertInfoInitInput")
	proto.RegisterType((*CertInfoInitOutput)(nil), "CertInfoInitOutput")
	proto.RegisterType((*CertInfoUpdateInput)(nil), "CertInfoUpdateInput")
	proto.RegisterType((*CertInfoUpdateOutput)(nil), "CertInfoUpdateOutput")
	proto.RegisterType((*StuInfoQueryInput)(nil), "StuInfoQueryInput")
	proto.RegisterType((*StuInfoQueryOutput)(nil), "StuInfoQueryOutput")
	proto.RegisterType((*StuGradeQueryInput)(nil), "StuGradeQueryInput")
	proto.RegisterType((*StuGradeQueryOutput)(nil), "StuGradeQueryOutput")
	proto.RegisterType((*StuActQueryInput)(nil), "StuActQueryInput")
	proto.RegisterType((*StuActQueryOutput)(nil), "StuActQueryOutput")
	proto.RegisterType((*StuCertQueryInput)(nil), "StuCertQueryInput")
	proto.RegisterType((*StuCertQueryOutput)(nil), "StuCertQueryOutput")
	proto.RegisterType((*ActInfoQueryInput)(nil), "ActInfoQueryInput")
	proto.RegisterType((*ActInfoQueryOutput)(nil), "ActInfoQueryOutput")
}

func init() { proto.RegisterFile("connect.proto", fileDescriptor_778b7e3040344da6) }

var fileDescriptor_778b7e3040344da6 = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x8a, 0xe4, 0x44,
	0x14, 0x4e, 0x7a, 0x7a, 0x7a, 0xec, 0xe3, 0xf6, 0xb2, 0x73, 0xfa, 0x67, 0xb2, 0x41, 0x64, 0x29,
	0xf6, 0x62, 0x45, 0x2c, 0x97, 0xf5, 0x07, 0x04, 0x59, 0x6d, 0xd7, 0x45, 0x06, 0x71, 0xd4, 0xb4,
	0xf3, 0x00, 0x99, 0x74, 0x39, 0xb4, 0x30, 0x49, 0x93, 0x54, 0x06, 0xe7, 0x29, 0x7c, 0x00, 0x51,
	0xbc, 0x10, 0xc4, 0x0b, 0x1f, 0xc3, 0x3b, 0x9f, 0xc7, 0x6b, 0xa9, 0x9f, 0x24, 0x55, 0x9d, 0x6a,
	0x63, 0x3b, 0xa0, 0x8d, 0x78, 0xd7, 0xa7, 0x92, 0x3a, 0x39, 0xdf, 0xa9, 0x73, 0xbe, 0xf3, 0x55,
	0xc3, 0x28, 0xc9, 0xd2, 0x94, 0x25, 0x9c, 0xae, 0xf3, 0x8c, 0x67, 0xe4, 0x7b, 0x1f, 0xee, 0x2d,
	0x78, 0x79, 0x9a, 0x7e, 0x99, 0x9d, 0xa6, 0x2b, 0x7e, 0x9a, 0xae, 0x4b, 0x8e, 0x13, 0x38, 0x14,
	0x6b, 0x1f, 0x06, 0xfe, 0x03, 0xff, 0x51, 0x3f, 0x52, 0x06, 0x06, 0x70, 0xb4, 0xe0, 0xe5, 0x59,
	0x7c, 0xc5, 0x82, 0xde, 0x03, 0xff, 0xd1, 0x30, 0xaa, 0x4c, 0x9c, 0xc1, 0xe0, 0xbc, 0x90, 0x0f,
	0x0e, 0xe4, 0x03, 0x6d, 0x09, 0x3f, 0x9f, 0xc4, 0x5f, 0x65, 0x79, 0xd0, 0x97, 0xcb, 0xca, 0x10,
	0x7e, 0x9e, 0x7f, 0xcd, 0xc5, 0x17, 0x83, 0x43, 0xe5, 0x47, 0x9b, 0x88, 0xd0, 0xff, 0x62, 0x75,
	0xc5, 0x82, 0x81, 0xfc, 0xac, 0xfc, 0x4d, 0x5e, 0x83, 0x63, 0x23, 0xbe, 0x4f, 0x4b, 0x2e, 0x02,
	0x14, 0xa1, 0x94, 0x49, 0xc2, 0x8a, 0x42, 0x86, 0x28, 0x42, 0x51, 0x26, 0xf9, 0xd1, 0x87, 0xd9,
	0x82, 0x97, 0x4b, 0x96, 0x4a, 0x97, 0xe7, 0xeb, 0x65, 0xcc, 0xd9, 0xfe, 0xa1, 0x7a, 0x1d, 0xc6,
	0x1a, 0x95, 0x8a, 0xb0, 0x13, 0xd7, 0x2f, 0xbe, 0xdc, 0xf1, 0x51, 0x1e, 0x2f, 0x59, 0xc4, 0x92,
	0x6c, 0xf9, 0x37, 0x41, 0x89, 0x60, 0x58, 0x7e, 0x25, 0x21, 0x8d, 0x22, 0xf9, 0x1b, 0x1f, 0xc2,
	0x68, 0x7e, 0xcd, 0xf2, 0xf8, 0x92, 0x49, 0xf7, 0x85, 0x04, 0x36, 0x8a, 0xec, 0xc5, 0x1d, 0x01,
	0x3e, 0x86, 0x89, 0x1d, 0xee, 0x4e, 0x08, 0x6f, 0x73, 0x6c, 0xff, 0x02, 0xc2, 0xbf, 0x78, 0x86,
	0x3f, 0xf9, 0x30, 0x9d, 0x27, 0x7c, 0x75, 0xbd, 0xe2, 0x37, 0x11, 0xbb, 0x5c, 0x15, 0x9c, 0xe5,
	0x35, 0xc6, 0x79, 0xc2, 0x35, 0xc6, 0x51, 0xa4, 0x0c, 0xe1, 0x69, 0x9e, 0x70, 0x13, 0xa3, 0x36,
	0xe5, 0x37, 0xd6, 0x59, 0x5a, 0x64, 0xb9, 0xae, 0xcd, 0xca, 0x14, 0x45, 0xbb, 0xe0, 0x31, 0x2f,
	0x0b, 0x5d, 0x9d, 0xda, 0xda, 0x11, 0xdb, 0x13, 0x98, 0x6d, 0x06, 0xda, 0x89, 0xee, 0x67, 0x1f,
	0x4e, 0xaa, 0x4d, 0x8e, 0xd6, 0xdb, 0x2b, 0x7c, 0x6f, 0x42, 0xd0, 0x0e, 0xb5, 0x13, 0xe1, 0x6f,
	0x7e, 0xb3, 0xcd, 0xd5, 0x88, 0x0e, 0x88, 0x75, 0xf1, 0xf6, 0x36, 0x8a, 0xb7, 0x02, 0x7e, 0xd0,
	0x06, 0xae, 0xcb, 0xba, 0x6f, 0x97, 0xf5, 0x4e, 0x00, 0x91, 0xc0, 0x9d, 0x79, 0xc2, 0x17, 0xab,
	0xcb, 0x34, 0xe6, 0x65, 0xce, 0x82, 0x23, 0xb9, 0xc5, 0x5a, 0x23, 0x6f, 0xc1, 0x7d, 0x07, 0x9a,
	0xce, 0x2c, 0x7c, 0xdb, 0x83, 0xe3, 0x67, 0x2c, 0xe7, 0xf6, 0xc8, 0x98, 0xc1, 0x40, 0x2e, 0x56,
	0x6d, 0xaa, 0xad, 0xed, 0x09, 0xa8, 0x60, 0x1e, 0x6c, 0x23, 0xdd, 0xbe, 0x9b, 0x74, 0x0f, 0x4d,
	0xd2, 0x7d, 0x09, 0x86, 0x82, 0xec, 0x6f, 0x6a, 0xfc, 0xc3, 0xa8, 0x59, 0xc0, 0x97, 0x01, 0x44,
	0x14, 0xba, 0x5e, 0x54, 0x0a, 0x8c, 0x15, 0x33, 0xa5, 0x2f, 0xb8, 0x53, 0x3a, 0x34, 0x52, 0xfa,
	0x10, 0x46, 0x72, 0x6f, 0x9d, 0x53, 0x90, 0x7b, 0xec, 0x45, 0x42, 0x01, 0xcd, 0xe4, 0x74, 0x66,
	0xf3, 0xbb, 0x1e, 0x8c, 0xab, 0x0d, 0x66, 0xc7, 0xfc, 0x9f, 0x4f, 0x95, 0xcf, 0xc7, 0x30, 0xb1,
	0xd3, 0xd3, 0x99, 0xd1, 0x57, 0x6a, 0xc1, 0xf0, 0x79, 0xc9, 0xf2, 0x9b, 0x3f, 0x19, 0x22, 0xe4,
	0x07, 0x1f, 0xd0, 0x7c, 0x57, 0xfb, 0xde, 0x27, 0xa1, 0xf0, 0x54, 0x46, 0x28, 0xfb, 0xb3, 0x0b,
	0x4e, 0x3d, 0xf9, 0x7a, 0xcd, 0xe4, 0xb3, 0xa6, 0xea, 0x6d, 0x30, 0xfe, 0x53, 0x53, 0xf5, 0xa9,
	0x94, 0xa3, 0xf3, 0x84, 0x77, 0xa2, 0xad, 0x09, 0xb7, 0x67, 0x10, 0x2e, 0xf9, 0xd5, 0x97, 0xc7,
	0x5f, 0x39, 0x68, 0xd0, 0xc6, 0x26, 0x39, 0xc7, 0x15, 0x39, 0x17, 0x66, 0x2f, 0x15, 0x55, 0x0e,
	0x62, 0x9b, 0x9c, 0xe3, 0x86, 0x9c, 0x0b, 0x9b, 0x9c, 0x8b, 0x86, 0x9c, 0x99, 0x8d, 0x91, 0x35,
	0x18, 0xb9, 0x81, 0x91, 0x6b, 0x72, 0x8e, 0x1d, 0xe4, 0x6c, 0xae, 0x91, 0x57, 0x25, 0x0c, 0x51,
	0xfa, 0x46, 0x22, 0xb6, 0x90, 0x02, 0xf9, 0x5d, 0xd5, 0x71, 0xfd, 0xb6, 0x46, 0xfd, 0x9f, 0xe7,
	0x10, 0xd1, 0xeb, 0xe2, 0xd8, 0x5b, 0xbd, 0xde, 0x3e, 0x6c, 0x71, 0x31, 0x40, 0xf3, 0xdd, 0xa6,
	0x32, 0xf6, 0x49, 0x99, 0x3c, 0xf9, 0xe6, 0x08, 0xe0, 0x59, 0xce, 0x96, 0x2b, 0x2e, 0x92, 0x82,
	0x6f, 0xc3, 0x8b, 0xc6, 0xed, 0x07, 0x8f, 0xe9, 0xe6, 0x5d, 0x2d, 0x44, 0xda, 0xba, 0x1e, 0x11,
	0x0f, 0xdf, 0x87, 0x91, 0x75, 0xbf, 0xc0, 0x13, 0xea, 0xbe, 0x15, 0x85, 0x13, 0xea, 0xb8, 0x88,
	0x10, 0x0f, 0xdf, 0x83, 0xbb, 0xb6, 0x80, 0x47, 0xf9, 0xe6, 0xa6, 0xee, 0x09, 0xa7, 0xd4, 0xa5,
	0xf3, 0x6d, 0x07, 0x3a, 0x86, 0xc6, 0x81, 0x19, 0xc0, 0x94, 0xba, 0x64, 0x34, 0xf1, 0xf0, 0x39,
	0xdc, 0xdb, 0x14, 0xa1, 0x38, 0xa3, 0x4e, 0x01, 0x1d, 0x9e, 0x50, 0xb7, 0x5e, 0x25, 0x1e, 0x7e,
	0x2c, 0xcf, 0x7d, 0x43, 0xeb, 0x61, 0x40, 0xb7, 0x68, 0xd5, 0xf0, 0x3e, 0xdd, 0x26, 0x0d, 0x89,
	0x87, 0x67, 0x30, 0x76, 0x68, 0x26, 0x6c, 0xf6, 0xb4, 0xf2, 0x13, 0xd2, 0xad, 0x22, 0x8b, 0x78,
	0xf8, 0x0e, 0xdc, 0x31, 0xe5, 0x02, 0x22, 0x6d, 0x49, 0xab, 0x70, 0x4c, 0xdb, 0x8a, 0x42, 0xe5,
	0xd7, 0x9e, 0x8c, 0x38, 0xa1, 0x0e, 0x25, 0x11, 0x4e, 0xa9, 0x6b, 0x80, 0xaa, 0x6f, 0x9b, 0xc3,
	0x0f, 0xeb, 0x4a, 0x6a, 0x7a, 0x29, 0x1c, 0xd3, 0xf6, 0x7c, 0x24, 0x1e, 0xbe, 0x2b, 0xcb, 0xab,
	0x19, 0x2a, 0x38, 0xa6, 0xed, 0x29, 0x15, 0x4e, 0xa8, 0x63, 0xf2, 0x10, 0x4f, 0x17, 0x75, 0x45,
	0xd1, 0xaa, 0xa8, 0x2d, 0xc6, 0x57, 0x45, 0x6d, 0x73, 0x78, 0x1d, 0x70, 0xcd, 0x72, 0x2a, 0x60,
	0x9b, 0x22, 0x55, 0xc0, 0x1b, 0x44, 0xa8, 0xb6, 0x9a, 0xcd, 0x8f, 0x48, 0x5b, 0xbc, 0x11, 0x8e,
	0x69, 0x9b, 0x1f, 0x88, 0xf7, 0xc1, 0x5d, 0x80, 0x8b, 0x24, 0x2b, 0x16, 0x2c, 0xbf, 0x66, 0xf9,
	0x67, 0xfe, 0xc5, 0x40, 0xfe, 0x71, 0xf2, 0xc6, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xa3,
	0x24, 0x7b, 0x49, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreditCertClient is the client API for CreditCert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreditCertClient interface {
	//学生信息初始化
	StuInfoInit(ctx context.Context, in *StuInfoInitInput, opts ...grpc.CallOption) (*StuInfoInitOutput, error)
	//学生信息更新
	StuInfoUpdate(ctx context.Context, in *StudentInfoUpdateInput, opts ...grpc.CallOption) (*StuInfoUpdateOutput, error)
	//各学期成绩录入
	StuGradeRecode(ctx context.Context, in *StuGradeRecodeInput, opts ...grpc.CallOption) (*StuGradeRecodeOutput, error)
	//各学期成绩更新
	StuGradeUpdate(ctx context.Context, in *StuGradeUpdateInput, opts ...grpc.CallOption) (*StuGradeUpdateOutput, error)
	//活动发布
	ActivityRegister(ctx context.Context, in *ActivityRegisterInput, opts ...grpc.CallOption) (*ActivityRegisterOutput, error)
	//活动信息更新
	ActivityInfoUpdate(ctx context.Context, in *ActivityInfoUpdateInput, opts ...grpc.CallOption) (*ActivityInfoUpdateOutput, error)
	//活动成绩录入
	ActivityGradeRecode(ctx context.Context, in *ActivityGradeRecodeInput, opts ...grpc.CallOption) (*ActivityGradeRecodeOutput, error)
	//证书信息初始化
	CertInfoInit(ctx context.Context, in *CertInfoInitInput, opts ...grpc.CallOption) (*CertInfoInitOutput, error)
	//证书信息更新
	CertInfoUpdate(ctx context.Context, in *CertInfoUpdateInput, opts ...grpc.CallOption) (*CertInfoUpdateOutput, error)
	//学生信息查询
	StuInfoQuery(ctx context.Context, in *StuInfoQueryInput, opts ...grpc.CallOption) (*StuInfoQueryOutput, error)
	//学生成绩查询
	StuGradeQuery(ctx context.Context, in *StuGradeQueryInput, opts ...grpc.CallOption) (*StuGradeQueryOutput, error)
	//学生活动查询
	StuActQuery(ctx context.Context, in *StuActQueryInput, opts ...grpc.CallOption) (*StuActQueryOutput, error)
	//学生证书查询
	StuCertQuery(ctx context.Context, in *StuCertQueryInput, opts ...grpc.CallOption) (*StuCertQueryOutput, error)
	//活动信息查询
	ActInfoQuery(ctx context.Context, in *ActInfoQueryInput, opts ...grpc.CallOption) (*ActInfoQueryOutput, error)
}

type creditCertClient struct {
	cc *grpc.ClientConn
}

func NewCreditCertClient(cc *grpc.ClientConn) CreditCertClient {
	return &creditCertClient{cc}
}

func (c *creditCertClient) StuInfoInit(ctx context.Context, in *StuInfoInitInput, opts ...grpc.CallOption) (*StuInfoInitOutput, error) {
	out := new(StuInfoInitOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuInfoInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuInfoUpdate(ctx context.Context, in *StudentInfoUpdateInput, opts ...grpc.CallOption) (*StuInfoUpdateOutput, error) {
	out := new(StuInfoUpdateOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuInfoUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuGradeRecode(ctx context.Context, in *StuGradeRecodeInput, opts ...grpc.CallOption) (*StuGradeRecodeOutput, error) {
	out := new(StuGradeRecodeOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuGradeRecode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuGradeUpdate(ctx context.Context, in *StuGradeUpdateInput, opts ...grpc.CallOption) (*StuGradeUpdateOutput, error) {
	out := new(StuGradeUpdateOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuGradeUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) ActivityRegister(ctx context.Context, in *ActivityRegisterInput, opts ...grpc.CallOption) (*ActivityRegisterOutput, error) {
	out := new(ActivityRegisterOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/ActivityRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) ActivityInfoUpdate(ctx context.Context, in *ActivityInfoUpdateInput, opts ...grpc.CallOption) (*ActivityInfoUpdateOutput, error) {
	out := new(ActivityInfoUpdateOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/ActivityInfoUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) ActivityGradeRecode(ctx context.Context, in *ActivityGradeRecodeInput, opts ...grpc.CallOption) (*ActivityGradeRecodeOutput, error) {
	out := new(ActivityGradeRecodeOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/ActivityGradeRecode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) CertInfoInit(ctx context.Context, in *CertInfoInitInput, opts ...grpc.CallOption) (*CertInfoInitOutput, error) {
	out := new(CertInfoInitOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/CertInfoInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) CertInfoUpdate(ctx context.Context, in *CertInfoUpdateInput, opts ...grpc.CallOption) (*CertInfoUpdateOutput, error) {
	out := new(CertInfoUpdateOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/CertInfoUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuInfoQuery(ctx context.Context, in *StuInfoQueryInput, opts ...grpc.CallOption) (*StuInfoQueryOutput, error) {
	out := new(StuInfoQueryOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuInfoQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuGradeQuery(ctx context.Context, in *StuGradeQueryInput, opts ...grpc.CallOption) (*StuGradeQueryOutput, error) {
	out := new(StuGradeQueryOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuGradeQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuActQuery(ctx context.Context, in *StuActQueryInput, opts ...grpc.CallOption) (*StuActQueryOutput, error) {
	out := new(StuActQueryOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuActQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) StuCertQuery(ctx context.Context, in *StuCertQueryInput, opts ...grpc.CallOption) (*StuCertQueryOutput, error) {
	out := new(StuCertQueryOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/StuCertQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCertClient) ActInfoQuery(ctx context.Context, in *ActInfoQueryInput, opts ...grpc.CallOption) (*ActInfoQueryOutput, error) {
	out := new(ActInfoQueryOutput)
	err := c.cc.Invoke(ctx, "/CreditCert/ActInfoQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditCertServer is the server API for CreditCert service.
type CreditCertServer interface {
	//学生信息初始化
	StuInfoInit(context.Context, *StuInfoInitInput) (*StuInfoInitOutput, error)
	//学生信息更新
	StuInfoUpdate(context.Context, *StudentInfoUpdateInput) (*StuInfoUpdateOutput, error)
	//各学期成绩录入
	StuGradeRecode(context.Context, *StuGradeRecodeInput) (*StuGradeRecodeOutput, error)
	//各学期成绩更新
	StuGradeUpdate(context.Context, *StuGradeUpdateInput) (*StuGradeUpdateOutput, error)
	//活动发布
	ActivityRegister(context.Context, *ActivityRegisterInput) (*ActivityRegisterOutput, error)
	//活动信息更新
	ActivityInfoUpdate(context.Context, *ActivityInfoUpdateInput) (*ActivityInfoUpdateOutput, error)
	//活动成绩录入
	ActivityGradeRecode(context.Context, *ActivityGradeRecodeInput) (*ActivityGradeRecodeOutput, error)
	//证书信息初始化
	CertInfoInit(context.Context, *CertInfoInitInput) (*CertInfoInitOutput, error)
	//证书信息更新
	CertInfoUpdate(context.Context, *CertInfoUpdateInput) (*CertInfoUpdateOutput, error)
	//学生信息查询
	StuInfoQuery(context.Context, *StuInfoQueryInput) (*StuInfoQueryOutput, error)
	//学生成绩查询
	StuGradeQuery(context.Context, *StuGradeQueryInput) (*StuGradeQueryOutput, error)
	//学生活动查询
	StuActQuery(context.Context, *StuActQueryInput) (*StuActQueryOutput, error)
	//学生证书查询
	StuCertQuery(context.Context, *StuCertQueryInput) (*StuCertQueryOutput, error)
	//活动信息查询
	ActInfoQuery(context.Context, *ActInfoQueryInput) (*ActInfoQueryOutput, error)
}

// UnimplementedCreditCertServer can be embedded to have forward compatible implementations.
type UnimplementedCreditCertServer struct {
}

func (*UnimplementedCreditCertServer) StuInfoInit(ctx context.Context, req *StuInfoInitInput) (*StuInfoInitOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuInfoInit not implemented")
}
func (*UnimplementedCreditCertServer) StuInfoUpdate(ctx context.Context, req *StudentInfoUpdateInput) (*StuInfoUpdateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuInfoUpdate not implemented")
}
func (*UnimplementedCreditCertServer) StuGradeRecode(ctx context.Context, req *StuGradeRecodeInput) (*StuGradeRecodeOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuGradeRecode not implemented")
}
func (*UnimplementedCreditCertServer) StuGradeUpdate(ctx context.Context, req *StuGradeUpdateInput) (*StuGradeUpdateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuGradeUpdate not implemented")
}
func (*UnimplementedCreditCertServer) ActivityRegister(ctx context.Context, req *ActivityRegisterInput) (*ActivityRegisterOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivityRegister not implemented")
}
func (*UnimplementedCreditCertServer) ActivityInfoUpdate(ctx context.Context, req *ActivityInfoUpdateInput) (*ActivityInfoUpdateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivityInfoUpdate not implemented")
}
func (*UnimplementedCreditCertServer) ActivityGradeRecode(ctx context.Context, req *ActivityGradeRecodeInput) (*ActivityGradeRecodeOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivityGradeRecode not implemented")
}
func (*UnimplementedCreditCertServer) CertInfoInit(ctx context.Context, req *CertInfoInitInput) (*CertInfoInitOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CertInfoInit not implemented")
}
func (*UnimplementedCreditCertServer) CertInfoUpdate(ctx context.Context, req *CertInfoUpdateInput) (*CertInfoUpdateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CertInfoUpdate not implemented")
}
func (*UnimplementedCreditCertServer) StuInfoQuery(ctx context.Context, req *StuInfoQueryInput) (*StuInfoQueryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuInfoQuery not implemented")
}
func (*UnimplementedCreditCertServer) StuGradeQuery(ctx context.Context, req *StuGradeQueryInput) (*StuGradeQueryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuGradeQuery not implemented")
}
func (*UnimplementedCreditCertServer) StuActQuery(ctx context.Context, req *StuActQueryInput) (*StuActQueryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuActQuery not implemented")
}
func (*UnimplementedCreditCertServer) StuCertQuery(ctx context.Context, req *StuCertQueryInput) (*StuCertQueryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuCertQuery not implemented")
}
func (*UnimplementedCreditCertServer) ActInfoQuery(ctx context.Context, req *ActInfoQueryInput) (*ActInfoQueryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActInfoQuery not implemented")
}

func RegisterCreditCertServer(s *grpc.Server, srv CreditCertServer) {
	s.RegisterService(&_CreditCert_serviceDesc, srv)
}

func _CreditCert_StuInfoInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuInfoInitInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuInfoInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuInfoInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuInfoInit(ctx, req.(*StuInfoInitInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentInfoUpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuInfoUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuInfoUpdate(ctx, req.(*StudentInfoUpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuGradeRecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuGradeRecodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuGradeRecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuGradeRecode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuGradeRecode(ctx, req.(*StuGradeRecodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuGradeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuGradeUpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuGradeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuGradeUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuGradeUpdate(ctx, req.(*StuGradeUpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_ActivityRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityRegisterInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).ActivityRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/ActivityRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).ActivityRegister(ctx, req.(*ActivityRegisterInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_ActivityInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityInfoUpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).ActivityInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/ActivityInfoUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).ActivityInfoUpdate(ctx, req.(*ActivityInfoUpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_ActivityGradeRecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityGradeRecodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).ActivityGradeRecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/ActivityGradeRecode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).ActivityGradeRecode(ctx, req.(*ActivityGradeRecodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_CertInfoInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertInfoInitInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).CertInfoInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/CertInfoInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).CertInfoInit(ctx, req.(*CertInfoInitInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_CertInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertInfoUpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).CertInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/CertInfoUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).CertInfoUpdate(ctx, req.(*CertInfoUpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuInfoQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuInfoQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuInfoQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuInfoQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuInfoQuery(ctx, req.(*StuInfoQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuGradeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuGradeQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuGradeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuGradeQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuGradeQuery(ctx, req.(*StuGradeQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuActQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuActQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuActQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuActQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuActQuery(ctx, req.(*StuActQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_StuCertQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuCertQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).StuCertQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/StuCertQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).StuCertQuery(ctx, req.(*StuCertQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCert_ActInfoQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActInfoQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCertServer).ActInfoQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreditCert/ActInfoQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCertServer).ActInfoQuery(ctx, req.(*ActInfoQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreditCert_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CreditCert",
	HandlerType: (*CreditCertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StuInfoInit",
			Handler:    _CreditCert_StuInfoInit_Handler,
		},
		{
			MethodName: "StuInfoUpdate",
			Handler:    _CreditCert_StuInfoUpdate_Handler,
		},
		{
			MethodName: "StuGradeRecode",
			Handler:    _CreditCert_StuGradeRecode_Handler,
		},
		{
			MethodName: "StuGradeUpdate",
			Handler:    _CreditCert_StuGradeUpdate_Handler,
		},
		{
			MethodName: "ActivityRegister",
			Handler:    _CreditCert_ActivityRegister_Handler,
		},
		{
			MethodName: "ActivityInfoUpdate",
			Handler:    _CreditCert_ActivityInfoUpdate_Handler,
		},
		{
			MethodName: "ActivityGradeRecode",
			Handler:    _CreditCert_ActivityGradeRecode_Handler,
		},
		{
			MethodName: "CertInfoInit",
			Handler:    _CreditCert_CertInfoInit_Handler,
		},
		{
			MethodName: "CertInfoUpdate",
			Handler:    _CreditCert_CertInfoUpdate_Handler,
		},
		{
			MethodName: "StuInfoQuery",
			Handler:    _CreditCert_StuInfoQuery_Handler,
		},
		{
			MethodName: "StuGradeQuery",
			Handler:    _CreditCert_StuGradeQuery_Handler,
		},
		{
			MethodName: "StuActQuery",
			Handler:    _CreditCert_StuActQuery_Handler,
		},
		{
			MethodName: "StuCertQuery",
			Handler:    _CreditCert_StuCertQuery_Handler,
		},
		{
			MethodName: "ActInfoQuery",
			Handler:    _CreditCert_ActInfoQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}
