@startuml
'https://plantuml.com/sequence-diagram
title 交易所流程（适用于回收报单撮合、梯次利用报单撮合、积分交易）
actor 卖方
actor 买方

== 积分交易 ==
卖方 -> 系统 : 提交积分报价交易
note left
这里的平台包含前端+应用层
不包含区块链
end note
系统 -> 区块链 : 部署积分交易合约
note left
交易发起人、最低成交金额、积分、
发起时间、竞价终止时间
end note
系统 <-- 区块链 : 合约地址
系统 -> 系统 : 保存合约地址
卖方 <-- 系统 : 返回信息

买方 -> 系统 : 查看交易列表，提出自己的报价
系统 -> 区块链 : 根据合约地址找到交易合约，添加自己的报价
note left
    竞价时间内进行
end note
系统 <-- 区块链 : 处理结果
买方 <-- 系统 : 返回信息

系统 -> 系统 : 定时器执行，找到竞价期结束的交易
系统 -> 区块链 : 根据合约地址找到交易合约，提出交易执行
note left
    合约里对竞价列表遍历，找<b>最高价格</b>
    记录交易信息，变更交易状态
    调用积分合约修改对应账户积分
end note
系统 <-- 区块链 : 处理结果
买方 <-- 系统 : 返回交易信息
卖方 <-- 系统 : 返回交易信息
note left
    站内信形式 or sth else
end note

@enduml