@startuml
'https://plantuml.com/sequence-diagram
title 用户登录
actor 用户

用户 -> Vue : 输入账户、密码
Vue -> Controller : /user/login
note left
md5密码加密
end note
Controller -> UserService : login
database Redis
UserService -> Redis : USER:LOCK:{USER_NAME}
UserService <-- Redis : 返回结果
alt 结果>5
    UserService --> Controller : 登录失败次数过多
end alt

database MySQL
UserService -> MySQL : 验证用户密码是否匹配
UserService <-- MySQL : 返回结果
alt 用户名密码不匹配
    UserService -> Redis : USER:LOCK:{USER_NAME} +1
    UserService --> Controller : 登录失败
end alt
UserService -> Shiro : 生成jwt token，记录用户信息
UserService -> MySQL : 查询角色和资源
UserService --> Controller : 返回角色和资源
Controller --> Vue : 登录成功
Vue --> 用户 : 登录成功，进入系统
@enduml