@startuml
'https://plantuml.com/sequence-diagram
title 用户注册
actor 用户

用户 -> Vue : 输入账户信息、密码、身份信息
note left
企业注册需要添加一些企业信息
end note
Vue -> Controller : /user/register
note left
md5密码加密
end note
Controller -> UserService : register
database MySQL
UserService -> MySQL : 检查账户、身份信息是否重复
UserService <-- MySQL : 返回结果
alt 账户信息重复
    Controller <-- UserService : 账户信息重复
    Vue <-- Controller : 返回结果
    用户 <-- Vue : 返回登录页
end alt

UserService -> JAVA_SDK : 创建非国密账户
note left
p12格式存储
密码为用户设置的账户密码
end note

UserService <-- JAVA_SDK : 返回账户的密钥对
'UserService -> WeIdentity : 根据密钥对生成weid
'UserService <-- WeIdentity : 返回weid

UserService -> MySQL : 数据持久化
note left
账户信息
关联文件/角色
end note
UserService <-- MySQL : 处理成功
Controller <-- UserService : 返回结果
Vue <-- Controller : 返回结果
用户 <-- Vue : 返回登录页

@enduml