@startuml
'https://plantuml.com/sequence-diagram

title 电池回收

'actor 原料商
actor 消费者
actor 车企或电池租赁商

actor 电池生产商
'actor 电池租赁商
actor 回收商

消费者 -> 车企或电池租赁商 : 电池置换
车企或电池租赁商 -> Vue : 提交回收单
电池生产商 -> Vue : 提交回收单
Vue -> Controller : 回收申请
Controller -> Service : 回收申请
Service -> JAVA_SDK : 部署回收委托合约
Service <-- JAVA_SDK : 返回合约地址

alt 指定回收商
Service -> JAVA_SDK : 获取BatteryContract合约
Service <-- JAVA_SDK : 返回合约地址
Service -> JAVA_SDK : BatteryContract.transfer
note left
    msg.sender=对应发起方
end note
Service <-- JAVA_SDK : 返回结果
end alt

alt 委托平台交易
    Service -> MySQL : 修改电池状态为交易中，防止重复绑定
end alt

database MySQL
Service -> MySQL : 持久化数据
note left
    回收委托单，关联电池信息
end note
Service <-- MySQL : 返回结果
Controller <-- Service :
Vue <-- Controller : 返回结果
车企或电池租赁商 <-- Vue : 返回结果
电池生产商 <-- Vue : 返回结果
note left
    指定回收商模式到此结束
    后续为委托平台撮合模式
end note

== 委托平台交易-竞价 ==
回收商 -> Vue : 查看回收单
Vue -> Controller :
Controller -> Service :
database MySQL
Service -> MySQL : 分页查询
Service <-- MySQL : 返回结果
Controller <-- Service :
Vue <-- Controller :
回收商 <-- Vue : 返回结果

回收商 -> Vue : 提交报价
Vue -> Controller : 回收单报价
Controller -> Service : 回收单报价
Service -> MySQL : 查询回收合约地址
Service <-- MySQL : 返回结果
Service -> JAVA_SDK : 获取回收委托合约
Service <-- JAVA_SDK : 返回结果
Service -> JAVA_SDK : 回收委托合约.竞价
Service <-- JAVA_SDK : 返回结果
note left
    如果达到期望金额，交易自动成交
end note
Controller <-- Service :
Vue <-- Controller :
回收商 <-- Vue : 返回结果

Service -> Service : 定时器扫描到期委托合约
Service -> JAVA_SDK : 获取回收委托合约
Service <-- JAVA_SDK : 返回结果
Service -> JAVA_SDK : 回收委托合约.交易成交
Service <-- JAVA_SDK : 返回结果

== 积分派发 ==
回收商 -> WeEvent : 扫码器或外部系统等设备批量录入流转信息
note left
    发布消息，回收相关变量
    topic: brecycle.battery.recycle
end note
Listener -> WeEvent : 订阅topic
Listener <-- WeEvent : 处理消息
note left
    积分派发给消费者
end note
Listener -> Service : 计算积分
Service -> JAVA_SDK : 获取PointController合约
Service <-- JAVA_SDK : 返回合约地址
Service -> JAVA_SDK : PointController.transfer
note left
    msg.sender=DAO
end note
Service <-- JAVA_SDK : 返回结果


@enduml