@startuml
'https://plantuml.com/sequence-diagram

title 电池生产

'actor 原料商
actor 电池生产商
actor 安全认证商
'actor 车企
'actor 消费者

== 电池生产环节 ==
alt 手动录入
    电池生产商 -> Vue : 手动录入电池信息
    Vue -> Controller : /battery/add
    Controller -> Service : 新增电池信息
else 传感器异步批量录入
    电池生产商 -> WeEvent : 扫码器等设备批量录入电池信息
    note left
        发布消息
        topic: brecycle.battery.add
    end note
    Listener -> WeEvent : 订阅topic
    Listener <-- WeEvent : 处理消息
    Listener -> Service : 新增电池信息
end alt

Service -> JAVA_SDK : 部署Battery合约
Service <-- JAVA_SDK : 返回合约地址
note left
    msg.sender=电池生产商
end note

Service -> JAVA_SDK : 获取PointController合约
Service <-- JAVA_SDK : 返回合约地址
Service -> JAVA_SDK : PointController.pay
note left
    msg.sender=DAO
end note
Service <-- JAVA_SDK : 返回结果

database MySQL
Service -> MySQL : 持久化数据
note left
    电池信息
end note
Service <-- MySQL : 返回信息

alt 手动录入
    Controller <-- Service : 返回信息
    Vue <-- Controller : 返回信息
    电池生产商 <-- Vue : 返回信息
end alt

== 安全认证环节 ==
安全认证商 -> WeEvent : 扫码器或外部系统等设备批量录入安全认证结果
note left
    发布消息
    topic: brecycle.battery.addSafeCheck
end note
Listener -> WeEvent : 订阅topic
Listener <-- WeEvent : 处理消息
Listener -> Service : 电池信息安全认证
Service -> JAVA_SDK : 获取BatteryContract合约
Service <-- JAVA_SDK : 返回合约地址
Service -> JAVA_SDK : BatteryContract.safeCheck
note left
    msg.sender=安全认证商
end note
Service <-- JAVA_SDK : 返回结果
Service -> MySQL : 更新状态
Service <-- MySQL : 返回结果

@enduml